### ISSUE TITLE
Refresh token is received null in login response

### ISSUE THREAD

**Issue by PBhuva** [okta/okta-oidc-xamarin#27] opened 2021-02-03 12:33 UTC
We are trying out Okta.Xamarin.iOS and Okta.Xamarin.Android (pre-release 1.0.0-beta02 SDK). After successful login the refresh token received in response is null.

## Current behavior
Refresh token received in response (i.e under StateManager object) is null. 
We are receiving values for only access token, id token, Expires, IsAuthenticated, Scope, TokenType properties.

## Expected behavior
Refresh token value should not be null.

## Minimal reproduction of the problem with instructions
1. Login using **OktaContext.Current.SignIn()** method. 
2. After successful login check response in SignInCompletion listener
3. Value for Refresh Token under StateManager object is null. 

## Environment
- OS:
    - iOS, Android
- Other:
      Visual Studio for Mac version 8.5.4(build 12)

**Comment by bryanapellanes-okta** [comment] 2021-02-03 13:33
@PBhuva ,
Thanks for reporting this issue.  I have a couple follow up questions to help us diagnose the issue:

- Are you using an emulator or a physical device?
- Can you share what instructions were used and what steps were taken to create the test app?
- Can you share code that reproduces the issue?
- Just to confirm, you're using Visual Studio for Mac, is that correct?

I've placed an item on our backlog to review this further, **OKTA-367333**.

**Comment by PBhuva** [comment] 2021-02-03 17:00
@bryanapellanes-okta , Please check the below response
* Are you using an emulator or a physical device?
    **We are using Physical device RealMeXT Android version 10.0 , Real device (XR) and iOS simulator**  
* Can you share what instructions were used and what steps were taken to create the test app? 
    **We have followed the implementation notes given with this GitHub project.**
* Can you share code that reproduces the issue? 
    **We are using the source code from this project and only replaced the Client Id, Okta domain and Redirect URI**
* Just to confirm, you're using Visual Studio for Mac, is that correct? 
    **We are using Visual Studio for Mac version 8.5.4**

**Comment by bryanapellanes-okta** [comment] 2021-02-03 18:11
@PBhuva ,
Thanks for your response.  Upon further review, it appears that handling of refresh tokens is not yet implemented in the current beta Xamarin Sdk.  I've placed an item on the backlog to address this in a future release.  In the mean time you may refer to the documentation on this topic at the following link should you choose to pursue your own implementation: https://developer.okta.com/docs/guides/refresh-tokens/get-refresh-token/

I apologize for the inconvenience, thanks for using Okta!

**Comment by bryanapellanes-okta** [comment] 2021-02-10 13:19
@PBhuva ,
Upon closer inspection, the absence of the refresh token may be due to a missing scope in the sign-in request.  I'm investigating further.

**Comment by bryanapellanes-okta** [comment] 2021-02-11 16:12
@PBhuva ,
Thanks for your patience!  After further investigation I found, in order to receive a refresh token on sign in, additional steps are necessary.  Those steps have been documented here: https://github.com/okta/okta-oidc-xamarin/pull/30/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R270

I expect this information will be merged shortly, but wanted to make you aware of my findings.

**Closed** 2021-02-11 16:25 UTC
Labels: OKTA-367333, pending-merge
