### ISSUE TITLE
App icon and launch screen are getting set to default icons after adding Okta.Xamarin.iOS package under .iOS app

### ISSUE THREAD

**Issue by PBhuva** [okta/okta-oidc-xamarin#29] opened 2021-02-04 14:27 UTC
We are trying out Okta.Xamarin.iOS and Okta.Xamarin.Android (pre-release 1.0.0-beta02 SDK). After adding Okta.Xamarin.iOS package to LaunchScreenTestApp.iOS project. The app icon and launch screen are getting overwritten by default icons provides by Xamarin.Forms

## Current behavior
App icon and launch screen is getting overwritten by default app icon provided by Xamarin.Forms after adding Okta.Xamarin.iOS (version 1.0.0-beta02).

App icon
![Screenshot 2021-02-04 at 7 35 19 PM](https://user-images.githubusercontent.com/62088523/106903689-4f2e9780-6720-11eb-9bef-7674dfc9c5bf.png)

Launch screen/spash screen
![Screenshot 2021-02-04 at 7 38 15 PM](https://user-images.githubusercontent.com/62088523/106903994-a9c7f380-6720-11eb-8592-5c91e26111d7.png)

## Expected behavior
Actual app icon and launch screen should be seen.

App icon
![Screenshot 2021-02-04 at 7 41 20 PM](https://user-images.githubusercontent.com/62088523/106904265-00353200-6721-11eb-9a4f-381585fce2ff.png)

Launch screen/spash screen
![Screenshot 2021-02-04 at 7 42 14 PM](https://user-images.githubusercontent.com/62088523/106904417-2c50b300-6721-11eb-8f5b-f4e4bb570236.png)

## Minimal reproduction of the problem with instructions
1.Set LaunchScreenTestApp.iOS as startup project and run the application.
2.App icon and launch screen will get set to default icon.
3.Remove Okta.Xamarin.iOS package from LaunchScreenTestApp.iOS project and delete bin obj from all projects.
4.Run the application.Actual app icon and launch screen will be shown

Sample Source Code: https://github.com/PBhuva/LaunchScreenTestApp

## Environment

- OS:
    iOS (Tested on iPhone XR 13.1.1 and iPhone 8plus 13.5 simulator)
- Other:
    Visual Studio for Mac version 8.5.4(build 12)

**Comment by bryanapellanes-okta** [comment] 2021-02-04 14:45
@PBhuva,
Thank you so much for reporting this, community feedback is critical to help us bring this beta Sdk to a fully featured state.  

I'm reviewing this now to determine appropriate corrective actions.  It may be necessary to correct this within the package itself, if this is the case I'll add an item to our backlog to address this in a future release.

**Comment by bryanapellanes-okta** [comment] 2021-02-04 15:21
@PBhuva 
It appears that this is caused by the `AppDelegate` defined in the `Okta.Xamarin.iOS` package;  I've entered an item to our backlog to address this in a future release.  In the mean time you may still use Okta for your project by removing the `Okta.Xamarin.iOS` reference (making sure to keep a reference to the `Okta.Xamarin` package) and adding the Okta related code from the `OktaDelegate` to your application delegate: 
https://github.com/okta/okta-oidc-xamarin/blob/master/Okta.Xamarin/Okta.Xamarin.iOS/OktaAppDelegate.cs
Note that the implementation for `IsOktaCallback` delegates to `OidcClient.InterceptLoginCallback` which is defined in `Okta.Xamarin`

**Comment by PBhuva** [comment] 2021-02-05 13:49
@BryanApellanes  Thank you for the response.

By removing Okta.Xamarin.iOS package and keeping only Okta.Xamarin package, it is giving me error at  **OktaContext.Init(new OidcClient(Window.RootViewController, OktaConfig.LoadFromPList("OktaConfigs.plist")));**  for OidcClient and OktaConfig method. So it is necessary to add OidcClient.cs, OidcClient.iOS.cs,OktaConfig.cs,OktaConfig.iOS.cs files as well?

**Comment by bryanapellanes-okta** [comment] 2021-02-05 14:18
@PBhuva ,
Yes, you should take the relevant code necessary, effectively moving the implementation out of the `Okta.Xamarin.iOS` package and into your own project.

**Comment by PBhuva** [comment] 2021-02-08 12:56
@bryanapellanes-okta  After adding OidcClient.cs, OidcClient.iOS.cs,OktaConfig.cs,OktaConfig.iOS.cs it seems to work.
But after login I am unable to get claims in BearerTokenClaims. It only gives Issuer, Subject, Audience, ExpirationTime & Scope.
So I tired to extract claims from access token using below method of **System.IdentityModel.Tokens.Jwt package**

 **public JwtSecurityToken ParseAuthenticationResult(string token)
  {
            var handler = new JwtSecurityTokenHandler();
            var tokens = handler.ReadJwtToken(token);
            return tokens;
  }**

But after adding this package it gives me error at Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(bytes); in OidcClient.cs
![Screenshot 2021-02-08 at 6 11 50 PM](https://user-images.githubusercontent.com/62088523/107221098-2f0d1a00-6a39-11eb-9bd6-172ae7aced6e.png)

It seems that Base64UrlEncoder.cs file has namespace Microsoft.IdentityModel.Tokens which is causing this issue. Can you please verify and let us know?
Also is there any other method to get all the claims?

**Comment by bryanapellanes-okta** [comment] 2021-02-08 13:45
> It seems that Base64UrlEncoder.cs file has namespace Microsoft.IdentityModel.Tokens which is causing this issue. Can you please verify and let us know?

It appears this file: https://github.com/okta/okta-oidc-xamarin/blob/master/Okta.Xamarin/Okta.Xamarin/Base64UrlEncoder.cs was included in the main package for a reason I don't understand.  A workaround you may try is to either create an identical implementation in a different namespace (essentially copy and paste the file into your project and change the namespace), alternatively you might try replacing the call to `Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(bytes)` with a call to the `WebEncoders.Base64UrlEncode(bytes)` method from `Microsoft.AspNetCore.WebUtilities.dll`, see:

- https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.webencoders.base64urlencode?view=aspnetcore-5.0
- https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webutilities.webencoders.base64urlencode?view=aspnetcore-5.0#Microsoft_AspNetCore_WebUtilities_WebEncoders_Base64UrlEncode_System_Byte___

> Also is there any other method to get all the custom claims which are configured (firstName,lastName, email, etc)?

There is an alternative way to get the claims information from the bearer token using Okta.Xamarin.Models.BearerToken, however this delegates to the `Base64UrlEncoder` class you referenced as causing an issue.  More information about custom claims is found here: https://developer.okta.com/docs/guides/customize-tokens-returned-from-okta/add-custom-claim/

Thank you again for your feedback and engagement.  As always thanks for using Okta!

**Comment by bryanapellanes-okta** [comment] 2021-02-08 13:46
@PBhuva see response above (forgot to tag you originally).

**Comment by bryanapellanes-okta** [comment] 2021-02-08 13:48
Added notes to internal ticket OKTA-367738 to address the presents of https://github.com/okta/okta-oidc-xamarin/blob/master/Okta.Xamarin/Okta.Xamarin/Base64UrlEncoder.cs.

**Comment by PBhuva** [comment] 2021-02-17 11:37
@BryanApellanes Could you please let us know by when can we get the new release with this fix? As of now workaround is working fine but it is almost like using files(i.e OidcClient.cs, OidcClient.iOS.cs,OktaConfig.cs,OktaConfig.iOS.cs) of Okta.Xamarin.iOS SDK into our actual code.

**Comment by bryanapellanes-okta** [comment] 2021-02-17 18:34
> @BryanApellanes Could you please let us know by when can we get the new release with this fix? As of now workaround is working fine but it is almost like using files(i.e OidcClient.cs, OidcClient.iOS.cs,OktaConfig.cs,OktaConfig.iOS.cs) of Okta.Xamarin.iOS SDK into our actual code.

We are investigating more deeply to ensure the issue is addressed systemically.

Alternatively to the workaround I provided, Microsoft provides documentation on how to specify `Alternate App Icons in Xamarin.iOS` here: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/alternate-app-icons.  This may allow you to reference the `Okta.Xamarin.iOS` package and still use an alternate app icon.

**Comment by PBhuva** [comment] 2021-02-18 13:35
@BryanApellanes 
Thank you for the response.
Below are my observations-
1. I tried the below workaround suggested by you. It does change the app icon but only when we tap on the icon. After installation is completed it shows blank icon and once we launch it then it changes the app icon.
2. Also once the app icon is set using an alternate method it displays system popup “You have changed the app icon for {App Name}”. Haven’t tried disabling this popup but I am not sure if Apple will reject the app if we try to disable this popup.
3. Launch screen issue still persists using this workaround.

**Comment by bryanapellanes-okta** [comment] 2021-02-18 14:15
> @BryanApellanes
> Thank you for the response.
> Below are my observations-
> 
> 1. I tried the below workaround suggested by you. It does change the app icon but only when we tap on the icon. After installation is completed it shows blank icon and once we launch it then it changes the app icon.
> 2. Also once the app icon is set using an alternate method it displays system popup “You have changed the app icon for {App Name}”. Haven’t tried disabling this popup but I am not sure if Apple will reject the app if we try to disable this popup.
> 3. Launch screen issue still persists using this workaround.

Thank you for taking the time to give that a try!  Additional investigation is needed to ensure this is addressed in a way that is intuitive and relevant for all consumers.

**Comment by bryanapellanes-okta** [comment] 2021-03-11 15:24
@PBhuva,
Thanks for your patience!  I wanted to give you a brief update.  I'm hoping to publish the next release soon, the code is currently in review here: #41

Once reviewed and merged the nuget packages will be published minutes later. Feel free to watch the pull request for updates.

If you are so inclined you can get early access to the nuget packages by downloading them from here: https://github.com/okta/okta-oidc-xamarin/tree/OKTA-360964-release-v1.0.0/nuget/packages

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment] 2021-07-01 15:55
Resolved by https://github.com/okta/okta-oidc-xamarin/pull/41

**Closed by bryanapellanes-okta** 2021-07-01 15:55 UTC
Labels: OKTA-346874
